#!/usr/bin/env node
/*
 * Migration factory PreToolUse guard.
 *
 * Two protections for the GeneXus → Spring Boot migration:
 *   1. regen-guard  — block any Write/Edit/NotebookEdit into the GeneXus-generated tree
 *                     (Receituario/JavaModel/web) or the Tomcat deploy tree. Those files are
 *                     regenerated by GeneXus and any edit is silently wiped. This enforces the
 *                     standing project rule.
 *   2. secret-scan  — block writing known-leaked DB credentials or literal (non-placeholder)
 *                     DB/JWT secrets into files destined for the new repo.
 *
 * Contract: receives the PreToolUse payload as JSON on stdin
 *   { tool_name, tool_input: { file_path, content?, new_string?, ... }, ... }
 * Exit 0 = allow. Exit 2 = block (stderr is shown to Claude as the block reason).
 */

import { readFileSync } from "node:fs";

function readStdin() {
  try { return readFileSync(0, "utf8"); } catch { return ""; }
}

const raw = readStdin();
let payload = {};
try { payload = JSON.parse(raw || "{}"); } catch { process.exit(0); } // fail-open on parse error

const toolName = payload.tool_name || "";
const input = payload.tool_input || {};
const filePath = input.file_path || input.path || input.notebook_path || "";

// Only guard file-writing tools.
const WRITE_TOOLS = ["Write", "Edit", "MultiEdit", "NotebookEdit"];
if (!WRITE_TOOLS.includes(toolName)) process.exit(0);

const norm = String(filePath).replace(/\\/g, "/");

// ---- 1. regen-guard: forbidden (regenerated) trees -------------------------
const FORBIDDEN = [
  "Receituario/JavaModel/web",          // GeneXus Java Model regen output
  "ReceituarioJavaEnvironment",         // Tomcat deploy tree
];
for (const f of FORBIDDEN) {
  if (norm.includes(f)) {
    process.stderr.write(
      `BLOCKED by regen-guard: '${filePath}' is inside a GeneXus-generated/deployed tree (matches "${f}").\n` +
      `These files are regenerated by GeneXus and any edit is wiped on the next Build All.\n` +
      `Real changes go in the KB (GeneXus IDE) or in the new app at receituario-modern/.\n`
    );
    process.exit(2);
  }
}

// ---- 2. secret-scan: leaked creds / literal secrets in repo files ----------
const content = input.content ?? input.new_string ?? "";
const text = String(content);

// Known leaked GeneXus credential blobs (from client.cfg — must never be copied forward).
const KNOWN_LEAKS = ["qVxDieU5ngJ", "dudhggSQtliZfx4F86JMacC8tMkXXXE9WGMHMnI"];
for (const leak of KNOWN_LEAKS) {
  if (text.includes(leak)) {
    process.stderr.write(
      `BLOCKED by secret-scan: '${filePath}' contains a known leaked GeneXus DB credential blob.\n` +
      `Do not propagate legacy secrets. Use env vars / Tomcat JNDI / a vault instead.\n`
    );
    process.exit(2);
  }
}

// Literal non-placeholder secrets being written into committed config.
// Allowed placeholders: ${...}, <...>, CHANGE_ME, env refs, empty.
const isPlaceholder = (v) =>
  !v || /^\s*$/.test(v) || /\$\{|<.*>|CHANGE_?ME|REPLACE|YOUR_|env:/i.test(v);
const SECRET_LINE = /^\s*(?:[A-Za-z0-9_.-]*(?:password|passwd|secret|jwt[._-]?secret|db[._-]?password|api[._-]?key))\s*[:=]\s*(.+)$/gim;
if (/\.(ya?ml|properties|env|json|ts|js|java)$/i.test(norm) && !/test|example|sample|README/i.test(norm)) {
  let m;
  while ((m = SECRET_LINE.exec(text)) !== null) {
    const val = m[1].trim().replace(/^["']|["'],?$/g, "");
    if (!isPlaceholder(val)) {
      process.stderr.write(
        `BLOCKED by secret-scan: '${filePath}' appears to hard-code a secret:\n  ${m[0].trim()}\n` +
        `Use an env-var placeholder (e.g. \${DB_PASSWORD}) and supply the value at runtime.\n`
      );
      process.exit(2);
    }
  }
}

process.exit(0);
